//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAKKIMIZDA
    {
        public short HAKKIMIZDAID { get; set; }
        public string HAKKIMIZDAACIKLAMA { get; set; }
        public string SPONSORRESIM { get; set; }
        public string SPONSORISIM { get; set; }
    }
}
