//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAPLAR()
        {
            this.SIPARISLER = new HashSet<SIPARISLER>();
            this.YORUMLAR = new HashSet<YORUMLAR>();
        }
    
        public int BARKOD { get; set; }
        public string KITAPADI { get; set; }
        public string KITAPRESMI { get; set; }
        public string KITAPACIKLAMA { get; set; }
        public Nullable<System.DateTime> YAYINTARIHI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> STOKMIKTARI { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public Nullable<int> YAZARID { get; set; }
        public Nullable<int> YAYINEVIID { get; set; }
    
        public virtual KATEGORILER KATEGORILER { get; set; }
        public virtual YAYINEVLERI YAYINEVLERI { get; set; }
        public virtual YAZARLAR YAZARLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARISLER> SIPARISLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YORUMLAR> YORUMLAR { get; set; }
    }
}
