//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikinciElKitapSatisEntities : DbContext
    {
        public ikinciElKitapSatisEntities()
            : base("name=ikinciElKitapSatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HAKKIMIZDA> HAKKIMIZDA { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
        public virtual DbSet<KATEGORILER> KATEGORILER { get; set; }
        public virtual DbSet<KITAPLAR> KITAPLAR { get; set; }
        public virtual DbSet<KULLANICILAR> KULLANICILAR { get; set; }
        public virtual DbSet<MESAJLAR> MESAJLAR { get; set; }
        public virtual DbSet<SATISLAR> SATISLAR { get; set; }
        public virtual DbSet<SIPARISLER> SIPARISLER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<YAYINEVLERI> YAYINEVLERI { get; set; }
        public virtual DbSet<YAZARLAR> YAZARLAR { get; set; }
        public virtual DbSet<YORUMLAR> YORUMLAR { get; set; }
    }
}
