//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATISLAR
    {
        public int SATISID { get; set; }
        public Nullable<int> KULLANICIID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> TOPLAMTUTAR { get; set; }
        public Nullable<int> SIPARISID { get; set; }
    
        public virtual SIPARISLER SIPARISLER { get; set; }
    }
}
