//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPARISLER()
        {
            this.SATISLAR = new HashSet<SATISLAR>();
        }
    
        public int SIPARISID { get; set; }
        public Nullable<int> KULLANICIID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> BIRIMTUTAR { get; set; }
        public Nullable<decimal> TOPLAMTUTAR { get; set; }
        public Nullable<int> ADET { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string EPOSTA { get; set; }
        public Nullable<int> BARKOD { get; set; }
    
        public virtual KITAPLAR KITAPLAR { get; set; }
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISLAR> SATISLAR { get; set; }
    }
}
