//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkinciElKitapSatis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YORUMLAR
    {
        public int YORUMID { get; set; }
        public Nullable<int> BARKOD { get; set; }
        public string YORUM { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> KULLANICIID { get; set; }
    
        public virtual KITAPLAR KITAPLAR { get; set; }
        public virtual KULLANICILAR KULLANICILAR { get; set; }
    }
}
